import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import Link from 'next/link'

import styles from './Layout.module.css'

const offsets = {
  '/': 0,
  '/about': 100
}

const Layout = ({ children }) => {
  const { pathname } = useRouter()
  const offset = offsets[pathname] || offsets['/']
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={styles.nav} style={{ transform: `translateX(${offset}px)` }}>
          <Link shallow href='/'>{'Home'}</Link>
          <Link shallow href='/about'>{'About'}</Link>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          {'footer'}
        </footer>
      </header>
    </>
  )
}

export default Layout