import Head from 'next/head'
import Link from 'next/link'

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link href='/'>{'Home'}</Link>
          <Link href='/about'>{'About'}</Link>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          {'footer'}
        </footer>
      </header>
    </>
  )
}

export default Layout